replicaCount: 4

image:
  repository: kubetest
  tag: v1
  # we're not publishing our container
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: kube.test
      paths:
        - /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
